version: '3'
services:
  guidance:
    image: guidance_server:gpu-0.3
    ports:
      - "9000:9000"
    volumes:
      - ./models:/models
    # Add the "labels" section to set the container to remove itself on shutdown
    labels:
      - "com.docker.compose.container-name=guidance-server"
      - "com.docker.compose.service=guidance-server"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=brainchulo-guidance-server"
    # Add the "stop_signal: SIGINT" option to use SIGINT signal for stopping the container gracefully
    stop_signal: SIGINT
    environment:
      MODEL_PATH: /models/vicuna-7B-1.1-GPTQ-4bit-128g
      # General Settings
      GENERAL_LOADING_METHOD: GPTQ
      GENERAL_BOOL_CPU_OFFLOADING: true

      # Tokenizer Settings
      TK_BOOL_USE_FAST: false

      # HuggingFace
      HF_BOOL_USE_QUANT: true
      HF_BOOL_USE_4_BIT: true

      # GPTQ
      GPTQ_INT_WBITS: 4
      GPTQ_INT_GROUP_SIZE: 128
      GPTQ_INT_PRE_LOADED_LAYERS: 20
      GPTQ_DEVICE: "cuda"
    deploy:
      resources:
        limits:
          memory: 28000M
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
