version: '3'
services:
  guidance:
    image: paolorechia/guidance_server:gpu-0.1
    ports:
      - "9000:9000"
    volumes:
      - ./models:/models
    # Add the "labels" section to set the container to remove itself on shutdown
    labels:
      - "com.docker.compose.container-name=guidance-server"
      - "com.docker.compose.service=guidance-server"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=brainchulo-guidance-server"
    # Add the "stop_signal: SIGINT" option to use SIGINT signal for stopping the container gracefully
    stop_signal: SIGINT
    environment:
      MODEL_PATH: models/vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g
      USE_GPTQ: true
      GPTQ_WBITS: 4
      GROUP_SIZE: 128
      GPTQ_DEVICE: cuda
    deploy:
      resources:
        limits:
          memory: 28000M
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
